# Generated by Django 3.2.9 on 2021-11-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField(blank=True, null=True, verbose_name='House ID')),
                ('size', models.IntegerField(blank=True, verbose_name='Size')),
                ('total_room', models.IntegerField(blank=True, null=True, verbose_name='No of Room')),
                ('bed', models.IntegerField(blank=True, null=True, verbose_name='No of Bed Room')),
                ('parking_lot', models.BooleanField(blank=True, verbose_name='Parking Lot')),
                ('floor', models.CharField(blank=True, max_length=5, verbose_name='Floor')),
            ],
            options={
                'verbose_name': 'House Details',
                'verbose_name_plural': 'House Details',
            },
        ),
    ]
