# Generated by Django 3.2.9 on 2021-12-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_housedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetails',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size'),
        ),
    ]
