# Generated by Django 3.2.9 on 2021-12-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_housedetails_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetails',
            name='parking_lot',
            field=models.CharField(blank=True, max_length=5, verbose_name='Parking Lot'),
        ),
    ]
