# Generated by Django 3.2.9 on 2021-12-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetails',
            name='parking_lot',
            field=models.BooleanField(blank=True, verbose_name='Parking Lot'),
        ),
    ]
