# Generated by Django 3.2.9 on 2021-12-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_housedetails_parking_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetails',
            name='parking_lot',
            field=models.BooleanField(default=False, verbose_name='Parking Lot'),
        ),
    ]
