# Generated by Django 3.2.9 on 2021-12-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_housedetails_parking_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedetails',
            name='house_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y%m%D/', verbose_name='Add House Image'),
        ),
    ]
