# Generated by Django 3.2.9 on 2021-12-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_housedetails_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedetails',
            name='location',
            field=models.CharField(blank=True, max_length=250, verbose_name='Location'),
        ),
    ]
