# Generated by Django 3.2.9 on 2021-12-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_housedetails_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetails',
            name='house_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/', verbose_name='Add House Image'),
        ),
    ]
