# Generated by Django 3.2.9 on 2021-12-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_housedetails_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housedetails',
            name='house_id',
        ),
        migrations.AddField(
            model_name='housedetails',
            name='house_name',
            field=models.TextField(blank=True, max_length=250, unique=True, verbose_name='House Name'),
        ),
        migrations.AddField(
            model_name='housedetails',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
