# Generated by Django 3.2.9 on 2021-12-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211224_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetails',
            name='house_name',
            field=models.TextField(blank=True, max_length=250, verbose_name='House Name'),
        ),
    ]
