# Generated by Django 3.2.9 on 2021-12-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_housedetails_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedetails',
            name='house_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='House ID'),
        ),
    ]
