# Generated by Django 3.2.9 on 2021-12-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_house_name_housedetails_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housedetails',
            old_name='name',
            new_name='title',
        ),
    ]
