# Generated by Django 3.2.9 on 2021-12-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_name_housedetails_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housedetails',
            old_name='title',
            new_name='house_name',
        ),
    ]
