# Generated by Django 3.2.9 on 2021-12-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_housedetails_house_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetails',
            name='house_name',
            field=models.TextField(default='', verbose_name='House Name'),
        ),
    ]
