# Generated by Django 3.2.9 on 2021-12-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20211226_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetails',
            name='house_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='House ID'),
        ),
    ]
