# Generated by Django 3.2.9 on 2021-12-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_housedetails_house_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housedetails',
            old_name='home',
            new_name='house_name',
        ),
    ]
