# Generated by Django 3.2.9 on 2021-12-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_home_housedetails_house_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetails',
            name='house_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='House Name'),
        ),
    ]
