# Generated by Django 3.2.9 on 2022-03-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_housedetails_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedetails',
            name='House_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Duplex', 'Duplex'), ('Commercial space', 'Commercial space'), ('Sublet', 'Sublet')], default=False, max_length=20, verbose_name='House Type'),
        ),
    ]
