# Generated by Django 3.2.9 on 2022-03-06 12:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_showmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houserate',
            old_name='infor_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='houserate',
            name='info_rate',
        ),
        migrations.RemoveField(
            model_name='houserate',
            name='info_review',
        ),
        migrations.AddField(
            model_name='houserate',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=750),
        ),
        migrations.AddField(
            model_name='houserate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houserate',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='houserate',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
