# Generated by Django 3.2.9 on 2022-03-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20220306_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houserate',
            options={'verbose_name': 'Rating And Review', 'verbose_name_plural': 'Ratings And Reviews'},
        ),
    ]
