# Generated by Django 3.2.9 on 2022-03-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20220309_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housedetails',
            name='house_id',
        ),
    ]
