# Generated by Django 3.2.9 on 2022-03-10 16:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20220310_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_house_name', models.CharField(blank=True, default='', max_length=50, verbose_name='House Name')),
                ('admin_size', models.IntegerField(blank=True, null=True, verbose_name='Size')),
                ('admin_total_room', models.IntegerField(blank=True, null=True, verbose_name='No of Room')),
                ('admin_bed', models.IntegerField(blank=True, null=True, verbose_name='No of Bed Room')),
                ('admin_parking_lot', models.BooleanField(default=False, verbose_name='Parking Lot')),
                ('admin_floor', models.CharField(blank=True, max_length=5, verbose_name='Floor')),
                ('admin_location', models.CharField(blank=True, max_length=250, verbose_name='Location')),
                ('admin_price', models.IntegerField(blank=True, null=True, verbose_name='Rent')),
                ('admin_house_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_image, verbose_name='Add House Image')),
                ('admin_user_photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_image, verbose_name='User profile picture')),
                ('admin_nid_front', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_image, verbose_name='NID front picture')),
                ('admin_nid_back', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_image, verbose_name='NID back picture')),
                ('admin_house_type', models.CharField(blank=True, max_length=20, verbose_name='House Type')),
            ],
            options={
                'verbose_name': 'Admin House Details',
                'verbose_name_plural': 'Admin House Details',
            },
        ),
    ]
